- hosts: default
  remote_user: vagrant
  sudo: true
  sudo_user: root

  tasks:

    ##
    # Update apt packages and add php 7 repo
    #
    - name: Add repositories
      apt_repository: repo='ppa:ondrej/php' state=present
      sudo: yes

    ##
    # Update apt packages
    #
    - name: General | Update apt packages.
      apt: update_cache=yes

    ##
    # Apt package instalation of required software
    #
    - name: General | Install required packages.
      apt: pkg={{ item }} state=present
      with_items:
        - build-essential
        - apache2
        - mysql-server-5.6
        - libapache2-mod-php7.0 
        - php7.0 
        - php7.0-common 
        - php7.0-gd 
        - php7.0-mysql 
        - php7.0-mcrypt 
        - php7.0-curl 
        - php7.0-intl 
        - php7.0-xsl 
        - php7.0-mbstring 
        - php7.0-zip 
        - php7.0-bcmath 
        - php7.0-iconv



    ##
    # Apache2 setup
    #
    - name: Apache | Enable required modules
      action: command a2enmod rewrite vhost_alias

    - name: Apache | Configuration file for our site
      action: template src=templates/etc-apache2-sites-available-website-conf.j2 dest=/etc/apache2/sites-available/website.conf

    - name: Apache | Disable the default site
      action: command a2dissite 000-default

    - name: Apache | Enable our new site
      action: command a2ensite website
      notify:
        - Restart Apache
    ##
    # Website setup
    #
    - name: Website | Set up file and directory permissions
      file: path=/vagrant/ mode=0777 recurse=yes state=directory
      sudo: yes

  ##
  # Restart services
  #
  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
